dist: bionic

language: php
php:
  - 7.4.7

before_script:
  - cp .env.travis .env
  - echo "USE mysql;\nALTER USER 'root'@'localhost' IDENTIFIED BY 'mysql';\n" | mysql -u root
  - mysql -u root -pmysql -e 'CREATE DATABASE IF NOT EXISTS `schoolman`;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv
  
script:
  - php artisan key:generate
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
  - jshint resources/assets/js/modules/*

cache:
  directories:
    - node_modules
    - vendor
