dist: bionic

language: php

php:
  - 7.4.7

services:
  - mysql

before_install:
  - echo "USE mysql;\nALTER USER 'root'@'localhost' IDENTIFIED BY 'mysql';\n" | mysql -u root
  - mysql -u root -pmysql -e 'CREATE DATABASE IF NOT EXISTS `schoolman`;'

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --seed
  - php artisan key:generate
  - php artisan jwt:secret

script:
  - vendor/bin/phpunit

cache:
  directories:
  - node_modules
  - vendor

deploy:
  provider: heroku
  api_key:
    secure: LCcAHLI6WNIoduodCC8tvRTIC/aKZLRlX2rQveSjtcWQOSXznMgc04qnc+3SYYrZX8qrA0uYwHYfBIooMMjYRv9a1tvG/CpPPXAD5xiDTk05PDxzQrMPArlSF7Vd7Q6vyL14gx8MCT6ZVOqkYgFgakFc8RsRGsG6yPAfYQGA1gkyRHNyP2vZ0DWhK2j4610zBvWNkC8DAAr9YVM+49070o0BU+S3Qs+OfPqFvnv8ixwdVqrj5eNelJUN21udinDZTuwp87tgsTQP7Qo8saqmJuAYtDqStIxGrRskzMrbql5sEl2PNfzrACQDiKmC1Q/Hp2tidyG10cnmYaZJXHwweSwaDIdPGBw37F0/TuWjr1fAnIQHsvjyU12OGoE/iE2gUwkNsnjTHFgYqizM2Ath5yUMDUmksGAV/oGZo/2cooWV9OD5qezmFPuKfeuYCBphxXDPF7XlDV+tt5TM0g6yDTcsME9Z4/BuZWk/GWinO7XuatNrX38k7Fp4TQTGdUuCkwP+TGKk7bTTseKHZ5Zk0YqI2JMmwcPMlydtsgz51w8qLuClfMKpmh4gNKhSnBOwteyEnzK98smfzfBhsnjlwA3EMscyWhC8nwm2cdHHvGvP5J+63u+x4ZG7+/hN3cEMK+MSxw4Lti4ehf4UUUQ6PSyna73dOlTAnxDl9mFaR0E=
  on: master
  app: schoolman-ub
